server:
  port: 8761
  address: 0.0.0.0


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



#ureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
