FROM openjdk:17
EXPOSE 8761

ADD target/mediconnect-service-registry.jar mediconnect-service-registry.jar
ENTRYPOINT ["java","-jar","/mediconnect-service-registry.jar"]


# Use the official OpenJDK image as a parent image
